name: blog_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_screenutil: ^5.0.2
  firebase_auth: ^3.3.4
  cloud_firestore: ^3.1.5
  firebase_core: ^1.10.6
  fluttertoast: ^8.0.8
  firebase_storage: ^10.2.4
  image_picker: ^0.8.4+4
  uuid: ^3.0.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

